const basicInfo = [
	{id: 'CYih7ZxVWm3W', basic: "GIVE SUPPORT", 							info: ""},
	{id: 'j2sMAvspATkt', basic: "Rate this add-on", 						info: "https://addons.mozilla.org/en-US/firefox/addon/universal-browser-manager"},
	{id: 'dp8rd3eEo8j7', basic: "GET SUPPORT", 								info: ""},
	{id: 'UXhcXndq7LVE', basic: "Homepage", 								info: "https://github.com/jzav/universal-browser-manager/"},
	{id: 'iCsvRNXuRSvi', basic: "Bugs and Feature requests",				info: "https://github.com/jzav/universal-browser-manager/issues"},
	{id: 'tRviRQsgK2uz', basic: "SHORTCUTS", 								info: ""},
	{id: 'HHoajVQ2d6t3', basic: "Alt + H", 									info: "load home (help) content"},
	{id: 'HiqajVQ2d6t3', basic: "Alt + B", 									info: "load folder manager"},
	{id: '5gwdjmCV3XKh', basic: "Alt + Q", 									info: "load saved queries"},
	{id: 'H2PR4ZTapst7', basic: "Alt + W", 									info: "load saved commands"},
	{id: 'epB6KEfcAVZG', basic: "Enter OR double-click row",				info: "focus tab (tabs mode)"},
	{id: 'gzh3ScjYwafL', basic: "Enter OR double-click row", 				info: "open closed tab in new tab (closed tabs mode)"},
	{id: 'yakvgJBSkLSs', basic: "Enter OR double-click row", 				info: "open bookmark in new tab (bookmarks mode)"},
	{id: '42Yc8jiFmc9a', basic: "Enter OR double-click row", 				info: "open history item in new tab (history mode)"},
	{id: '2J5fWcZ8EGVA', basic: "Enter OR double-click row", 				info: "open url in new tab (clipboard mode)"},
	{id: 'wdtEiJa8RW5s', basic: "Enter OR double-click row", 				info: "execute saved query (query manager)"},
	{id: 'gSmCKY5U6kut', basic: "Enter OR double-click row", 				info: "execute saved command (command manager)"},
	{id: 'xai86HniVZjW', basic: "Enter OR double-click row", 				info: "copy info column value (home)"},
	{id: 'xaisdHniVZjW', basic: "Double-click folder", 						info: "load folder content (folder manger)"},
	{id: 'xaisdH9aVZjW', basic: "Click folder", 							info: "select folder (folder manger)"},
	{id: '9D29ZsB8JNkw', basic: "Click grid row favicon", 					info: "un/select item"},
	{id: 'nhyeWyyBpQgU', basic: "Ctrl + Click grid row", 					info: "un/select item"},
	{id: 'zGtow53Kfgpr', basic: "Space", 									info: "un/select item (when grid row is focused)"},
	{id: 'Cmmo4AKBJBwM', basic: "Shift + Up/Down",							info: "un/select item (when grid row is focused)"},
	{id: 'GvY9z6CjXsCN', basic: "Shift + Home", 							info: "un/select all items from focused row to top"},
	{id: 'ZAvTxDgik85B', basic: "Shift + End", 								info: "un/select all items from focused row to bottom"},
	{id: 'cfg2r77JhWtC', basic: "Shift + Click", 							info: "un/select items between focused and clicked rows"},
	{id: 'CGs7zigYVfuY', basic: "Click grid header checkbox", 				info: "un/select all items"},
	{id: 'XSu72Wqb4wN2', basic: "Ctrl + A",									info: "select all items (when grid row is focused)"},
	{id: 'XSsdfsdf4wN2', basic: "Ctrl + U", 								info: "unselect all items (when grid row is focused)"},
	{id: 'bxDdJonQWAkg', basic: "Ctrl + I", 								info: "invert selection (when grid row is focused)"},
	{id: 'mjcU8uGcGWNX', basic: "Alt + Up", 								info: "focus search box"},
	{id: 'EWCjmbG92q6J', basic: "Ctrl + Up", 								info: "clear search box filters"},
	{id: 'SeyNH4N6nEya', basic: "Ctrl + Alt + Up OR Alt + Home",			info: "clear all search box content"},
	{id: 'cHd7WbS3g5sd', basic: "Tab", 										info: "normalize query (when search box is focused)"},
	{id: 'Y9vZCbmAMCHT', basic: "Enter", 									info: "execute query (when search box is focused)"},
	{id: 'KGT4WRA4niX8', basic: "Alt + Down", 								info: "focus command box"},
	{id: '562fBUvk86YX', basic: "Ctrl + (Alt +) Down or Alt + End",			info: "clear all command box content"},
	{id: 'Y9vZCbmAMCHT', basic: "Enter", 									info: "execute command (when commands box is focused)"},
	{id: 'mQjQxUZErJDe', basic: "F4 OR Alt + E", 							info: "edit cell value (when editable column cell is focused)"},
	{id: '99eZP42mEVsc', basic: "Esc", 										info: "discard changes (when editing cell value)"},
	{id: 'xeFNLTYgU8d4', basic: "Enter", 									info: "commit changes (when editing cell value)"},
	{id: 'F6soKrLFpkBw', basic: "Alt + Left", 								info: "focus most left column cell in last active (or first) item in grid"},
	{id: 'wsa2v7PsdzLE', basic: "Alt + Right", 								info: "focus most right column cell in last active (or first) item in grid"},
	{id: 'u7yA94bX8n3C', basic: "Home", 									info: "focus first column cell (when column cell is focused)"},
	{id: '9eSAb7Py9wqd', basic: "End", 										info: "focus last column cell (when column cell is focused)"},
	{id: 'ASAyGUF3kXW5', basic: "Alt + A", 									info: "sort column ascending (when column cell is focused)"},
	{id: '4SFAbeeszWHK', basic: "Alt + S", 									info: "reset to default sorting (when column cell is focused)"},
	{id: 'n484dW8xuiX6', basic: "Alt + D", 									info: "sort column descending (when column cell is focused)"},
	{id: 'pfzuF9RPQvoo', basic: "Alt + Y", 									info: "hide all columns except for focused one and auto-size it to fit content"},
	{id: 'q3yJcwovaSaG', basic: "Alt + X ",									info: "auto-size focused column to fit content"},
	{id: 'XeQ2WsAkeYPX', basic: "Alt + C ",									info: "auto-size all columns to fit content (when column cell is focused)"},
	{id: 'Rz8WZx67QtTv', basic: "Alt + V",									info: "reset columns state (when column cell is focused)"},
	{id: 'cKKepqgDE33c', basic: "LIBRARIES (LICENSES)", 					info: ""},
	{id: 'QeRtm4JyCoSD', basic: "ag-Grid (MIT)", 							info: "https://www.ag-grid.com"},
	{id: 'auuJrLJ9RsUu', basic: "async.js (MIT)", 							info: "https://caolan.github.io/async/index.html"},
	{id: 'Tjooi6byGFVv', basic: "Bootstrap (MIT)", 							info: "https://getbootstrap.com/"},
	{id: 'Tjooi6byGFVx', basic: "Font Awesome code (MIT)", 					info: "https://fontawesome.com/"},
	{id: 'Tjooi6byGFVf', basic: "Lodash (MIT)", 							info: "https://lodash.com/"},
	{id: 'eE2hxsf7nAyN', basic: "moment.js (MIT)", 							info: "https://momentjs.com"},
	{id: 'ucBQdN74ucUX', basic: "ICONS", 									info: ""},
	{id: 'W8kzRPtrgRMf', basic: "Bookmark icon (CC BY 4.0)", 				info: "https://www.iconarchive.com/show/childish-icons-by-double-j-design/Bookmark-icon.html"},
	{id: 'Tjooi6byGFVq', basic: "Font Awesome fonts (SIL OFL 1.1)", 		info: "https://fontawesome.com/"},
	{id: 'Tjooi6TTGFVq', basic: "Material icons (Apache-2.0)", 				info: "https://fonts.google.com/icons"},
	{id: 'ucBQd584ucUX', basic: "OTHER", 									info: ""},
	{id: 'ucBQd132ucUX', basic: "Folder Tree Component inspired by (MIT)", 	info: "https://github.com/akalp/bs5-nav-tree/tree/v0.3.1"},
];
